// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimpleStorage$Type } from "./SimpleStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleStorage"]: SimpleStorage$Type;
    ["contracts/SimpleStroage.sol:SimpleStorage"]: SimpleStorage$Type;
  }

  interface ContractTypesMap {
    ["SimpleStorage"]: GetContractReturnType<SimpleStorage$Type["abi"]>;
    ["contracts/SimpleStroage.sol:SimpleStorage"]: GetContractReturnType<SimpleStorage$Type["abi"]>;
  }
}
