// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SimpleStorage$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SimpleStorage",
  "sourceName": "contracts/SimpleStroage.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "newValue",
          "type": "uint256"
        }
      ],
      "name": "ValueUpdated",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "getValue",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "setValue",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600e575f5ffd5b5060df80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c80632096525514603457806355241077146048575b5f5ffd5b5f5460405190815260200160405180910390f35b605760533660046093565b6059565b005b5f8190556040518181527f4273d0736f60e0dedfe745e86718093d8ec8646ebd2a60cd60643eeced5658119060200160405180910390a150565b5f6020828403121560a2575f5ffd5b503591905056fea2646970667358221220225145ad50ac36c9780d4adcfef152a6e271eeacb612da13ce6f8d2ed293f02564736f6c634300081b0033",
  "deployedBytecode": "0x6080604052348015600e575f5ffd5b50600436106030575f3560e01c80632096525514603457806355241077146048575b5f5ffd5b5f5460405190815260200160405180910390f35b605760533660046093565b6059565b005b5f8190556040518181527f4273d0736f60e0dedfe745e86718093d8ec8646ebd2a60cd60643eeced5658119060200160405180910390a150565b5f6020828403121560a2575f5ffd5b503591905056fea2646970667358221220225145ad50ac36c9780d4adcfef152a6e271eeacb612da13ce6f8d2ed293f02564736f6c634300081b0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SimpleStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SimpleStorage$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/SimpleStroage.sol:SimpleStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SimpleStorage$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SimpleStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SimpleStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/SimpleStroage.sol:SimpleStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SimpleStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SimpleStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SimpleStorage$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/SimpleStroage.sol:SimpleStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SimpleStorage$Type["abi"]>>;
}
